version: "3.3"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
      args:
        - DEV=1
    image: django-backend
    command: sh -c "/app/scripts/migrate_and_run"
    volumes:
        - "./db:/app/db"
    ports:
      - 8000:8000
    env_file:
      - .env


