version: "3.3"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
    image: django-backend
    command: sh -c "/app/scripts/migrate_and_run"
    volumes:
        - "./assets:/app/assets"
        - "./media:/app/media"
        - "./main/migrations:/app/main/migrations"
        - "dbdata:/app/db"
    ports:
      - "8010:8000"
    extra_hosts:
            - "host.docker.internal:host-gateway"
    env_file:
      - .env.prod

volumes:
        dbdata:
