version: "3.3"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
    image: django-backend
    command: sh -c "/app/scripts/migrate_and_run"
    volumes:
        - "./db:/app/db"
        - "./assets:/app/assets"
        - "./media:/app/media"
    ports:
      - "8010:8000"
    env_file:
      - .env.prod


